// Curated emoji set with keywords for search
export type EmojiEntry = { char: string; name: string };

export const EMOJIS_BY_CATEGORY: { label: string; icon: string; emojis: string[] }[] = [
    {
        label: 'Smileys',
        icon: '😀',
        emojis: ['😀', '😃', '😄', '😁', '😆', '😅', '🤣', '😂', '🙂', '🙃', '😉', '😊', '😇', '🥰', '😍', '🤩', '😘', '😗', '😚', '😙', '🥲', '😋', '😛', '😜', '🤪', '😝', '🤑', '🤗', '🤭', '🤫', '🤔', '🤐', '🤨', '😐', '😑', '😶', '🙄', '😏', '😒', '🤥', '😔', '😌', '😪', '😴', '😷', '🤒', '🤕', '🤢', '🤮', '🤧', '🥵', '🥶', '😵', '🤯', '🤠', '🥳', '😎', '🤓', '🧐', '😕', '😟', '🙁', '☹️', '😮', '😯', '😲', '😳', '🥺', '😦', '😧', '😨', '😰', '😥', '😢', '😭', '😱', '😖', '😣', '😞', '😓', '😩', '😫', '🥱', '😤', '😡', '😠', '🤬', '😈', '👿', '💀', '☠️', '💩', '🤡', '👹', '👺', '👻', '👽', '👾', '🤖'],
    },
    {
        label: 'Gestures',
        icon: '👋',
        emojis: ['👋', '🤚', '🖐️', '✋', '🖖', '👌', '🤌', '🤏', '✌️', '🤞', '🤟', '🤘', '🤙', '👈', '👉', '👆', '👇', '☝️', '👍', '👎', '✊', '👊', '🤛', '🤜', '👏', '🙌', '👐', '🤲', '🤝', '🙏', '💪', '🦾', '🫶', '🫂'],
    },
    {
        label: 'People',
        icon: '👤',
        emojis: ['😺', '😸', '😹', '😻', '😼', '😽', '🙀', '😿', '😾', '🙈', '🙉', '🙊', '👶', '🧒', '👦', '👧', '🧑', '👱', '👨', '🧔', '👩', '🧓', '👴', '👵', '🙍', '🙎', '🙅', '🙆', '💁', '🙋', '🧏', '🙇', '🤦', '🤷'],
    },
    {
        label: 'Hearts',
        icon: '❤️',
        emojis: ['❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍', '🤎', '💔', '❣️', '💕', '💞', '💓', '💗', '💖', '💘', '💝', '💟', '☮️', '✝️', '🕉️', '🔯', '♈', '♉', '♊', '♋', '♌', '♍', '♎', '♏', '♐', '♑', '♒', '♓'],
    },
    {
        label: 'Celebrate',
        icon: '🎉',
        emojis: ['🎉', '🎊', '🎈', '🎁', '🎀', '🪅', '🎆', '🎇', '✨', '🌟', '⭐', '💫', '🏆', '🥇', '🥈', '🥉', '🏅', '🎖️', '🎗️', '🎫', '🎟️', '🎪', '🎭', '🎨', '🎬', '🎤', '🎧', '🎼', '🎹', '🥁', '🎷', '🎺', '🎸', '🪕', '🎻'],
    },
    {
        label: 'Nature',
        icon: '🌿',
        emojis: ['🌸', '🌺', '🌻', '🌹', '🌷', '🌱', '🌲', '🌳', '🌴', '🌵', '🌾', '🍀', '🍁', '🍂', '🍃', '🪷', '🍄', '🌊', '🌋', '🏔️', '⛰️', '🗻', '🏕️', '🌅', '🌄', '🌠', '🌌', '🌈', '⛅', '🌤️', '🌩️', '❄️', '☃️', '🌬️', '🌀'],
    },
    {
        label: 'Animals',
        icon: '🦁',
        emojis: ['🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼', '🐨', '🐯', '🦁', '🐮', '🐷', '🐸', '🐵', '🙈', '🙉', '🙊', '🐔', '🐧', '🐦', '🦆', '🦅', '🦉', '🦇', '🐺', '🦄', '🦋', '🐛', '🐝', '🐌', '🦗', '🐞', '🦟', '🦎', '🐍', '🐢', '🦖', '🦕', '🐙', '🦑', '🦞', '🦀', '🐠', '🐟', '🐡', '🐬', '🦭', '🐳', '🦈', '🐊', '🦧', '🦣', '🐘', '🦒', '🦓', '🦏', '🐪', '🦘', '🦬'],
    },
    {
        label: 'Food',
        icon: '🍕',
        emojis: ['🍕', '🍔', '🌮', '🌯', '🥗', '🍜', '🍣', '🍱', '🍛', '🍤', '🍿', '🧁', '🍰', '🎂', '🍩', '🍪', '🍫', '🍬', '🍭', '🍦', '🍧', '🍨', '🍺', '🍻', '🥂', '🍷', '🍸', '🍹', '☕', '🍵', '🧃', '🥤', '🧋', '🥩', '🍗', '🍖', '🥓', '🥚', '🍳', '🥞', '🧇', '🥐', '🥖', '🧀', '🥗', '🥘', '🍲', '🫕', '🥫'],
    },
    {
        label: 'Travel',
        icon: '✈️',
        emojis: ['✈️', '🚀', '🛸', '🚁', '🛶', '⛵', '🚢', '🚂', '🚆', '🚇', '🚊', '🚉', '🚓', '🚑', '🚒', '🚐', '🚌', '🚎', '🚕', '🚗', '🚙', '🏎️', '🚜', '🏍️', '🛵', '🛺', '🚲', '🛴', '🛹', '🛼', '🛷', '⛷️', '🏂', '🪂', '🚵', '🧗', '🏋️', '⚽', '🏀', '🏈', '⚾', '🎾', '🏐', '🏉', '🎱', '🏓', '🏸', '🥊', '🤸'],
    },
    {
        label: 'Objects',
        icon: '💡',
        emojis: ['📱', '💻', '⌨️', '🖥️', '🖨️', '🖱️', '💾', '💿', '📷', '📸', '📹', '🎥', '📞', '☎️', '📺', '📻', '⏰', '⌛', '⏳', '💡', '🔧', '🔨', '⚙️', '🔑', '🔒', '🔓', '💌', '📧', '📝', '📋', '📁', '📂', '💰', '💳', '💎', '⚡', '🔥', '🎮', '🕹️', '🧩', '🎲', '♟️', '🎯', '🎳'],
    },
    {
        label: 'Symbols',
        icon: '💯',
        emojis: ['💯', '✅', '❌', '❎', '🔴', '🟠', '🟡', '🟢', '🔵', '🟣', '⚫', '⚪', '🟤', '🔺', '🔻', '💠', '🔷', '🔹', '🔶', '🔸', '▶️', '⏩', '⏭️', '⏯️', '◀️', '⏪', '⏮️', '🔼', '⏫', '🔽', '⏬', '⏸️', '⏹️', '⏺️', '🎦', '🔅', '🔆', '📶', '📳', '📴', '📵', '✔️', '💲', '💱', '〽️', '♻️', '✳️', '❇️', '🆕', '🆓', '🆙', '🆒', '🆗', '🆙', '🔞', '📵', '🚳'],
    },
];

// Flat list for search
export const EMOJI_SEARCH: EmojiEntry[] = [
    { char: '😀', name: 'grinning face happy smile' },
    { char: '😃', name: 'smiley face happy big eyes' },
    { char: '😄', name: 'smile happy joy laugh grinning' },
    { char: '😁', name: 'grin happy beam smile' },
    { char: '😆', name: 'laughing happy satisfied haha' },
    { char: '😅', name: 'sweat smile nervous laugh' },
    { char: '🤣', name: 'rofl rolling floor laughing haha' },
    { char: '😂', name: 'tears joy laugh crying funny' },
    { char: '🙂', name: 'slight smile happy' },
    { char: '😉', name: 'wink flirt smile' },
    { char: '😊', name: 'blush smile happy sweet' },
    { char: '😇', name: 'innocent halo angel smile' },
    { char: '🥰', name: 'smiling hearts love adore' },
    { char: '😍', name: 'heart eyes love beautiful amazing' },
    { char: '🤩', name: 'star struck wow amazing excited' },
    { char: '😘', name: 'face blowing kiss love' },
    { char: '😎', name: 'cool sunglasses confident' },
    { char: '🥳', name: 'partying face celebrate birthday' },
    { char: '😏', name: 'smirk smug clever' },
    { char: '😒', name: 'unamused bored unhappy' },
    { char: '😢', name: 'crying sad tears' },
    { char: '😭', name: 'loudly crying sad very upset' },
    { char: '😤', name: 'puffing triumph frustrated' },
    { char: '😡', name: 'angry pout red face mad' },
    { char: '🤬', name: 'cursing face swearing angry' },
    { char: '🥺', name: 'pleading face puppy eyes sad cute' },
    { char: '😱', name: 'screaming fear shocked omg' },
    { char: '🤯', name: 'exploding head mind blown wow' },
    { char: '🥲', name: 'smiling tear happy sad bittersweet' },
    { char: '😴', name: 'sleeping tired zzz' },
    { char: '🤔', name: 'thinking hmm pondering wonder' },
    { char: '🤗', name: 'hugging face hug love' },
    { char: '🫶', name: 'heart hands love' },
    { char: '👍', name: 'thumbs up like good yes ok approve' },
    { char: '👎', name: 'thumbs down dislike no bad' },
    { char: '👏', name: 'clapping hands applause bravo' },
    { char: '🙌', name: 'raising hands celebrate hooray' },
    { char: '🤝', name: 'handshake agreement deal' },
    { char: '🙏', name: 'folded hands please thank pray' },
    { char: '💪', name: 'flexed biceps strong muscle' },
    { char: '🔥', name: 'fire hot lit trending flame' },
    { char: '✨', name: 'sparkles magic shiny star' },
    { char: '💯', name: 'hundred percent perfect score' },
    { char: '❤️', name: 'red heart love' },
    { char: '🧡', name: 'orange heart' },
    { char: '💛', name: 'yellow heart' },
    { char: '💚', name: 'green heart' },
    { char: '💙', name: 'blue heart' },
    { char: '💜', name: 'purple heart' },
    { char: '🖤', name: 'black heart' },
    { char: '💔', name: 'broken heart sad' },
    { char: '💕', name: 'two hearts love couple' },
    { char: '🎉', name: 'party popper celebrate tada' },
    { char: '🎊', name: 'confetti ball celebrate' },
    { char: '🎁', name: 'gift present birthday' },
    { char: '🏆', name: 'trophy win champion' },
    { char: '⭐', name: 'star favorite rating' },
    { char: '🌟', name: 'glowing star bright' },
    { char: '✅', name: 'check mark done yes correct' },
    { char: '❌', name: 'cross no wrong cancel' },
    { char: '💡', name: 'light bulb idea' },
    { char: '🚀', name: 'rocket launch space' },
    { char: '🍕', name: 'pizza food' },
    { char: '☕', name: 'hot beverage coffee tea' },
    { char: '🍺', name: 'beer drink cheers' },
    { char: '🎮', name: 'video game controller gaming' },
    { char: '💻', name: 'laptop computer work' },
    { char: '📱', name: 'mobile phone cell' },
    { char: '📷', name: 'camera photo picture' },
    { char: '🌈', name: 'rainbow colorful' },
    { char: '🌊', name: 'wave ocean water' },
    { char: '⛅', name: 'cloud sun partly cloudy weather' },
    { char: '❄️', name: 'snowflake cold winter snow' },
    { char: '🌸', name: 'cherry blossom flower spring' },
    { char: '🦋', name: 'butterfly beautiful nature' },
    { char: '🐶', name: 'dog puppy pet animal' },
    { char: '🐱', name: 'cat kitten pet animal' },
    { char: '🦁', name: 'lion king animal' },
    { char: '🐼', name: 'panda cute animal' },
    { char: '🦊', name: 'fox animal' },
    { char: '🎵', name: 'music note song' },
    { char: '🎶', name: 'musical notes song music' },
    { char: '💤', name: 'zzz sleep tired snooze' },
    { char: '👀', name: 'eyes looking watching see' },
    { char: '💯', name: 'perfect hundred score' },
    { char: '😈', name: 'smiling devil mischief evil' },
    { char: '👻', name: 'ghost spooky halloween' },
    { char: '💩', name: 'poop pile funny' },
    { char: '🤡', name: 'clown face funny silly' },
    { char: '👑', name: 'crown king queen royal' },
    { char: '💎', name: 'gem diamond jewel rich' },
    { char: '🎯', name: 'direct hit target bullseye' },
    { char: '🧩', name: 'puzzle piece strategy' },
];
